Release 4.5.1
blackbaud/skyux-ag-grid pull request #99
Opened 2021-02-10 22:10 UTC by Blackbaud-TrevorBurch

2021-02-10 22:29 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-ag-grid?_sp.spa=pr-release-4.5.1](https://developer.blackbaud.com/skyux-ag-grid?_sp.spa=pr-release-4.5.1)

2021-02-11 12:44 UTC, blackbaud-paulah commented on CHANGELOG.md
> +- Fixed the ag-grdi wrapper to properly handle keyboard navigation while a master/detail grid is being used. [#98](https://github.com/blackbaud/skyux-ag-grid/pull/98)
```suggestion
- Fixed the ag-grid wrapper to properly handle keyboard navigation while a master/detail grid is being used. [#98](https://github.com/blackbaud/skyux-ag-grid/pull/98)
```

2021-02-11 12:48 UTC, blackbaud-paulah requested changes
There was a minor typo in the changelog. I noted it in the suggestion.

2021-02-11 19:20 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-ag-grid?_sp.spa=pr-release-4.5.1](https://developer.blackbaud.com/skyux-ag-grid?_sp.spa=pr-release-4.5.1)

2021-02-11 19:48 UTC, blackbaud-paulah approved these changes

2021-02-11 20:00 UTC, blackbaud-johnly approved these changes

2021-02-11 20:12 UTC, merged